version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  apt_packages:
  - libcurl4-openssl-dev
  jobs:
    post_system_dependencies:
    - git clone -b release https://github.com/roswell/roswell.git
    - (cd roswell && sh bootstrap &&  ./configure --prefix=$HOME/.local && make && make install)
    - mkdir -p ~/quicklisp/local-projects
    - (cd ~/quicklisp/local-projects && git clone https://github.com/simoninireland/cl-bitfields.git)

python:
  install:
  - requirements: requirements.txt

sphinx:
  configuration: doc/conf.py
