version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  apt_packages:
  - jq
  jobs:
    post_system_dependencies:
    - curl -L https://github.com/roswell/roswell/releases/download/v23.10.14.114/roswell_23.10.14.114-1_amd64.deb --output roswell.deb
    - sudo dpkg -i roswell.deb

python:
  install:
  - requirements: requirements.txt

sphinx:
  configuration: doc/conf.py
