version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  apt_packages:
  - libcurl4-openssl-dev
  jobs:
    post_system_dependencies:
    - git clone -b release --depth 1 https://github.com/roswell/roswell.git
    - (cd roswell && sh bootstrap &&  ./configure --prefix=$HOME/.local && make && make install)
    - $HOME/.local/bin/ros install sbcl
    - mkdir -p ~/.roswell/lisp/quicklisp/local-projects
    - (cd ~/.roswell/lisp/quicklisp/local-projects && git clone --depth 1 https://github.com/simoninireland/cl-bitfields.git)

python:
  install:
  - requirements: requirements.txt

sphinx:
  configuration: doc/conf.py
